# This is a basic workflow to help you get started with Actions

name: buildandUpdate

# Controls when the workflow will run
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 0 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set TimeZone
        run: sudo timedatectl set-timezone 'Asia/Shanghai'
      
      - name: Printout GITHUB_WORKSPACE
        run: |
          echo $GITHUB_WORKSPACE

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 14.x
          
      - name: Checkout excalidraw-build
        uses: actions/checkout@v2
        with:
          path: excalidraw-build

      - name: Clone excalidraw-excalidraw
        run: |
          git clone https://github.com/excalidraw/excalidraw.git $GITHUB_WORKSPACE/excalidraw-excalidraw

      # Runs a set of commands using the runners shell
      - name: setup and build
        run: |
          cd $GITHUB_WORKSPACE/excalidraw-excalidraw/
          npm install -g json
          npm install gh-pages --save
          json -I -f package.json -e "this.private=true"
          json -I -f package.json -e "this.homepage=\"./\""
          npm install
          npm run build
          rm -rf $GITHUB_WORKSPACE/excalidraw-build/*
          mv $GITHUB_WORKSPACE/excalidraw-excalidraw/build/* $GITHUB_WORKSPACE/excalidraw-build/          
          
      - name: Push files
        run: |
          cd $GITHUB_WORKSPACE/excalidraw-build/
          git config user.name maxduke
          git config user.email maxduke@gmail.com
          git add -A
          git commit -m "sync. files on `date +'%Y-%m-%d %H:%M:%S'`"
          git push
